#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Mon Nov 28 18:03:41 2016

@author: rubyvazquez
"""
#1.	Create a list named my_list in python with the following data points 
my_list = [45.4, 44.2, 36.8, 35.1, 39.0, 60.0, 47.4, 41.1, 45.8, 35.6]
#a.	Print the 5th element in the list
my_list[4]
#b.	Append 55.2 to my_list
my_list.append(55.2)
#c.	Remove the 6th element in the list
my_list.pop(5)
#d.	Iterate over the list to print data points greater than 45
for i in range(0,10):
    if my_list[i]>45:
        print(my_list[i])
#2.	Introduction to numpy – 
#a.	Import the numpy library using the following command
import numpy
#b.	Declare numpy array with the same data points as in my_list using
numpy.array(my_list)
#c.	Compute the mean and standard deviation using 
numpy.mean(my_list)
numpy.std(my_list) 
#d.	Use logical referencing to get only those values that are less than 45
result = []
for i in range(0,10):
    result.append(my_list[i]<45)
    
result = numpy.array(result)
mylist = numpy.array(my_list)
mylist[result]
#e.	Compute the max and min of the array using
numpy.max(my_list)
numpy.min(my_list)
#3.	Introduction to pandas – 
#a.	Import the pandas library – 
import pandas
#b.	Read the IRIS dataset into iris using pandas.read_csv()
iris = pandas.read_csv("/Users/rubyvazquez/Desktop/SMU/Doing Data Science/Unit 11/iris.csv")
#c.	Using iris.head(), display the head of the dataset
iris.head()
#d.	Use DataFrame.drop() to drop the id column
iris = iris.drop('Id', 1) 
#e.	Subset dataframe to create a new data frame that includes only the measurements for the setosa species
iris1 = iris.query('Species == "Iris-setosa"')
#f.	Use DataFrame.describe() to get the summary statistics
iris.describe()
#g.	Use DataFrame.groupby() to create grouped data frames by Species and compute summary statistics using DataFrame.describe()
iris.groupby(['Species']).describe()
#h.	Use DataFrame.boxplot() to plot boxplots by Species
iris.groupby(['Species']).boxplot()

#i.	Plot a scatter matrix plot using the seaborn library. Use the following to load and plot 
import seaborn as sns
sns.pairplot(iris,hue='Species')


